#!/bin/bash

if [ "$EUID" -eq 0 ]; then
    echo "Please don't run this as root."
    exit 1
fi

set -euxo pipefail

rm ~/.bashrc ~/.profile
stow Home -t ~/

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak remote-modify flathub --enable

flatpak install -y flathub com.dec05eba.gpu_screen_recorder com.valvesoftware.Steam \
    md.obsidian.Obsidian org.prismlauncher.PrismLauncher