#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "Please run this as root."
  exit 1
fi

set -euxo pipefail

apt remove thunderbird redshift pix seahorse sticky libreoffice-* thingy \
	hypnotix hexchat firefox simple-scan 

apt-get update
apt-get install ca-certificates curl
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
  bookworm stable" | \
  tee /etc/apt/sources.list.d/docker.list > /dev/null

wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg \
    | gpg --dearmor \
    | dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg

echo 'deb [arch=amd64,arm64 signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg] https://download.vscodium.com/debs vscodium main' \
    | tee /etc/apt/sources.list.d/vscodium.list

apt update && apt install -y mpv mpv-mpris mosh codium keepassxc wireshark \
	chromium virt-manager flatseal stow

usermod -aG libvirt melonlorrd
usermod -aG docker melonlorrd
usermod -aG wireshark melonlorrd