#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "Please run this as root."
  exit 1
fi

set -euxo pipefail

dnf upgrade -y

dnf copr enable -y brycensranch/gpu-screen-recorder-git
dnf copr enable -y solopasha/hyprland
dnf copr enable -y sneexy/zen-browser

dnf install -y \
	https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
	https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

rpmkeys --import https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg

cat <<EOF | tee -a /etc/yum.repos.d/vscodium.repo
[gitlab.com_paulcarroty_vscodium_repo]
name=download.vscodium.com
baseurl=https://download.vscodium.com/rpms/
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
metadata_expire=1h
EOF

dnf install --setopt=install_weak_deps=False -y hyprland

dnf install brightnessctl network-manager-applet mako swaybg hyprpolkitagent \
    xdg-desktop-portal-hyprland wofi swaylock swayidle greetd tuigreet waybar

dnf install -y zen-browser kitty keepassxc gpu-screen-recorder-gtk codium fragments \
    mpv mpv-mpris flatseal 

dnf install -y stow podman podman-compose @development-tools golang virt-manager \
    wireshark kubernetes1.32-client ansible opentofu helm micro wl-clipboard \
    SDL2-devel 

usermod -aG libvirt melonlorrd
usermod -aG wireshark melonlorrd

dnf swap -y ffmpeg-free ffmpeg --allowerasing
dnf swap -y mesa-va-drivers mesa-va-drivers-freeworld --allowerasing
dnf swap -y mesa-vdpau-drivers mesa-vdpau-drivers-freeworld --allowerasing